name: G'd Up Code
description: Programming/Software Development & Related
meta_description: "Programming, Software Development and Related"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'iluxonchik.github.io'
author:         'ILUXONCHIK'
